source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

target 'LT_Timer' do
    pod 'Alamofire', '~> 4.7'
    pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git'
end
